name: CI

on:
  push:
    branches:
      - master
      - dev
    path-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - 'docs/**'
      - 'maps/**'
      - 'CREDITS'
      - 'LICENSE'
      - '**.md'
  pull_request:
    path-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - 'docs/**'
      - 'maps/**'
      - 'CREDITS'
      - 'LICENSE'
      - '**.md'

env:
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure
      run: cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}} --parallel 2
